modules/ting_search_carousel/js/ting_search_carousel.js, modules/ting_search_carousel/ting_search_carousel.admin.inc, modules/ting_search_carousel/ting_search_carousel.module
Ting search carousel automatic tab switch logic.
=> DDBEASY-761 - Backend settings for the auto-animate tabs delay.

modules/ding_toggle_format/ding_toggle_format.module
Fix user pages, add module permissions.
=> DDBEASY-742 - Ding toggle format changes.

modules/ding_redirect/ding_redirect.admin.inc
Changing maxlength of textfield for redirect url in admin form.
=> DAB-9 - Error on login page.

modules/ding_event/ding_event.module, modules/ding_event/ding_event.views_default.inc
=> Revert "EASYOPAC-67 - New event widget: Full-page calendar."

ding2.make
=> EASYOPAC-218 - Update modules.

modules/ding_campaign/ding_campaign.module
=> Revert "Hotfix - Adds support MKWS functionality."

easyopac.make
=> Revert "Ding reading club"

modules/ting_search_carousel/js/jquery.rs.carousel.js, modules/ting_search_carousel/js/jquery.ui.touch-punch.min.js, modules/ting_search_carousel/templates/ting_search_carousel.tpl.php, modules/ting_search_carousel/ting_search_carousel.module, modules/ting_search_carousel/ting_search_carousel.theme.inc
Changed functionality of ting_search_carousel from easyopac in order to make it work with new easySuite development and also with p2/ting_carousel.
=> EASYOPAC-222 - Adapting ting_search_carousel.

modules/ding_mobilesearch/ding_mobilesearch.module
Export to mobilesearch event all date flag and site timezone.
=> ES-958 - Include all day flag and timezone into event date exports.

modules/ting_search_autocomplete/includes/ting_search_autocomplete.ajax.inc
=> Revert "EASYOPAC-464 - Adding correct header to request."

modules/ding_event/ding_event.field_group.inc, modules/ding_place2book/ding_place2book.install, modules/ding_place2book/ding_place2book.module, themes/ddbasic/sass/components/node/event.scss
https://platform.dandigbib.org/issues/1404
=> More Place2book fixes

ding2.make, modules/ting_search/plugins/content_types/search_result_count.inc, themes/ddbasic/templates/node/node--ding-campaign.tpl.php, themes/ddbasic/templates/node/node--ding-event.tpl.php
Cherry-picked from https://github.com/ding2/ding2/pull/996.
=> 1996 by Inlead: Adapting MKWS and MKDRU to ding2.

modules/alma/alma.module
https://github.com/ding2/ding2/pull/550
=> 1721: Add support for filtering on holdings

themes/ddbasic/scripts/menu.js
Reverts easySuite/ding2#421
This PR is reverted because the problem is in the easyddb_search_expand module
=> Revert " EASYOPAC-500 - Remove overlay on ipe button click."

modules/ding_place2book/ding_place2book.module
This pattern now occurs multiple places and this provides a nice
documented API which simplifies code and avoids duplication.
=> 3704: Implement function for retrieving place2book id for a node

modules/ding_place2book/ding_place2book.module
http://platform.dandigbib.org/issues/1340
=> 1340 by Inlead: Bigger image export to Kultunaut.

modules/ding_place2book/ding_place2book.admin.inc
https://platform.dandigbib.org/issues/2146
=> 2146: Improve configuration of Place2book endpoints

modules/ding_place2book/ding_place2book.module, themes/ddbasic/sass/components/node/event.scss
https://platform.dandigbib.org/issues/3819
=> 3819 by Inlead: Fix the display of P2b states.

modules/ding_place2book/ding_place2book.module
http://platform.dandigbib.org/issues/3296
=> 3296 by Inlead: Implement waiting list state.

modules/ding_place2book/ding_place2book.install
https://platform.dandigbib.org/issues/1404
Fixes some issues with the migration of the old standard settings. See comments on code for more info.
=> 1404: Fix some issues with migration of settings

modules/ding_place2book/ding_place2book.module
https://platform.dandigbib.org/issues/3819
First attempt to fix event state in new p2b module.
=> 1404: Fix event state

modules/ding_place2book/ding_place2book.admin.inc, modules/ding_place2book/lib/p2b/P2b.php
Changes to p2b endpoint configuration and how they are stored as requested by code review.
=> 1404: Change p2b endpoint config as requested

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.module
Some small fixes in relation to the recent p2b-API changes: https://docs.google.com/spreadsheets/d/1PLyDLT6F86PY6AMkBmW0R_wh8bgOkC3SiHbyrTTxwRA/edit#gid=0
=> 1404 api changes fixes

modules/ding_content/ding_content.pages_default.inc, modules/ding_event/ding_event.pages_default.inc, modules/ding_frontend/ding_frontend.pages_default.inc, modules/ding_frontpage/ding_frontpage.pages_default.inc, modules/ding_groups/ding_groups.pages_default.inc, modules/ding_library/ding_library.pages_default.inc, modules/ding_news/ding_news.pages_default.inc, modules/ding_page/ding_page.pages_default.inc, modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module, modules/ding_ting_frontend/ding_ting_frontend.pages_default.inc, modules/ding_user_frontend/ding_user_frontend.pages_default.inc, modules/ting_infomedia/ting_infomedia.pages_default.inc
https://inlead.atlassian.net/browse/EASYOPAC-1029
We have "campaign" added on many of our Panels. These should be replaced by "ding_campaign_plus".
=> EASYOPAC-1029 - Convert all our campaigns to campaign_plus.

modules/ding_place2book/ding_place2book.admin.inc, modules/ding_place2book/lib/p2b/P2b.php
Apparently some things went wrong with the rebase. This PR correct these.
=> 1404: Fixes after rebase

modules/ding_nodelist/ding_nodelist.module
https://inlead.atlassian.net/browse/EASYOPAC-1038
This is a prod issue. Events in the node in blocks widget show the previous date for the all day items.
=> HOTFIX - Consider timezone for all day events.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-420
Added the new module for Wayfinder to our Make-file in order to be able to install/enable it on sigtes.
=> EASYOPAC-420 - Add Wayfinder module to Make-file.

modules/ting_search_carousel/plugins/content_types/carousel.inc, modules/ting_search_carousel/ting_search_carousel.install
=> Revert "EASYOPAC-1030 - Rename search key configs variable."

modules/ting_search_carousel/ting_search_carousel.install
=> Revert "EASYOPAC-1030 - Migrate ting_searches to the searches settings."

modules/ting_search_carousel/ting_search_carousel.install
=> Revert "Revert "EASYOPAC-1030 - Migrate ting_searches to the searches settings.""

modules/ting/js/ting.js, themes/ddbasic/scripts/menu.js
https://inlead.atlassian.net/browse/EASYOPAC-1051
Fixing appeared gap between main menu and search bar.
=> EASYOPAC-1051 - Fix empty gap between menu and search.

modules/ding_availability/js/ding_availability.js, modules/ding_availability/js/ding_availability_labels.js
https://inlead.atlassian.net/browse/EASYOPAC-1070
Strings provided by ding_availability module are not translated.
=> EASYOPAC-1070 - Make ding_availability listen to current language.

culture.make, ding2.make, modules/ding_event/ding_event.features.field_instance.inc
https://inlead.atlassian.net/browse/EASYOPAC-1061?focusedCommentId=67216&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-67216
General fixes.
=> EASYOPAC-1061 - Dev issues fixes.

ding2.install, ding2.make, ding2.profile
https://inlead.atlassian.net/browse/EASYOPAC-1092
This module fixes the problem when in webform node is configured one "Email address" in "From" field and email is sent from site default email address.
=> EASYOPAC-1092 - Add 'Mimemail' module.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-375
It should be possible for the user to select more facets.
If the user click on the new button "Vælg flere" (select more) a popup should be opened where the user can select MULTIPLE facets and click on search. This will make an OR search.
If the user don't open the popup but just select facets directly from the list in the left side, then the search will be AND (like it is today).
=> EASYOPAC-375 - Add easyopac facets modules to the make file.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1099
Add easyopac_facets_translate module to the make file.
Module implementation and task description is in the module repository.
=> EASYOPAC-1099 - Add Facets Translate module to make file.

modules/ding_mobilesearch/ding_mobilesearch.module
https://inlead.atlassian.net/browse/ES-1799
Push language code alongside the node content.
Void.
=> ES-1799 - Push language value.

modules/p2/ding_entity_rating/ding_entity_rating.module, modules/p2/ding_entity_rating/js/ding_entity_rating_widget.js
https://inlead.atlassian.net/browse/EASYOPAC-1145
"Thank you" message wasn't translated for ding_entity_rating actions.
=> EASYOPAC-1145 - Translate ding_entity_rating message.

modules/ding_availability/ding_availability.module, modules/ding_availability/js/ding_availability_labels.js
https://inlead.atlassian.net/browse/EASYOPAC-1146
On search result collection items was observed inconsistency in rendering of materials availability labels.
=> EASYOPAC-1146 - Fix inconsistency of availability types.

modules/ding_event/ding_event.module, modules/ding_event/templates/views-exposed-form-widget--date-inputs.tpl.php, modules/ding_event/templates/views-exposed-form-widget--title.tpl.php, modules/ding_event/templates/views-exposed-form-widget.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1115
Added templates for Event list exposed filters.
=> EASYOPAC-1115 - Provide templates for exposed filters.

modules/ding_mobilesearch/ding_mobilesearch.module
https://inlead.atlassian.net/browse/EASYOPAC-1170
Check mobilesearch push flag before reacting on scheduled publish.
None.
None.
=> EASYOPAC-1170 - Check node's flag.

modules/ting/ting.field.inc
https://inlead.atlassian.net/browse/EASYOPAC-1099
Provide translation for the attached language to the title field of the ting object.
NOTE: Could not add translation outside of ding2 core, ie in a separate module.
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> EASYOPAC-1099 - Translate attached language.

modules/opensearch/src/OpenSearchTingObject.php
https://inlead.atlassian.net/browse/EASYOPAC-1099
Use the unique name for string.
=> EASYOPAC-1099 - Use the unique name for string.

themes/ddbasic/sass/components/class.scss
https://platform.dandigbib.org/issues/4571
Added icons for social links in the page event and styled them.
=> EASYOPAC-1166 - Added icons for social links.

modules/ding_availability/ding_availability.module
https://inlead.atlassian.net/browse/EASYOPAC-1165
Allow altering of item containing availability data by other modules.
=> EASYOPAC-1165 - Highlight specific holding location.

modules/ding_campaign/ding_campaign.module
https://inlead.atlassian.net/browse/EASYOPAC-1101
Remove array sort
=> EASYOPAC-1101 - Remove array sort.

easyopac.make
https://inlead.atlassian.net/browse/EE-41
Added module to make file.
=> EE-41 - Add module to make file.

ding2.make, modules/ding_event/ding_event.module
https://inlead.atlassian.net/browse/EASYOPAC-874
=> EASYOPAC-874 - Clone: Added 'Clone' tab on node page.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-374
Add search by subjects.
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> EASYOPAC-374 - Add ting_search_subject module to make file.

modules/ding_app_variables/ding_app_variables.module
https://inlead.atlassian.net/browse/EASYOPAC-1183
Include all carousels in the JSON exported variable
=> EASYOPAC-1183 - Get all pane carousel configurations.

modules/ding_base/ding_base.module, modules/ding_event/ding_event.features.field_instance.inc
https://inlead.atlassian.net/browse/EASYOPAC-1110
Update date field format.
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> EASYOPAC-1110 - Update field formatter for event date.

modules/ding_sections/ding_sections.module
None. Hotfix.
Wrap section processing in an explicit check whether to do it. Minor error scenarios checking
None.
None.
=> EASYOPAC-NO_TASK - Minor error-proof checks.

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/sass/ding_nodelist.scss
https://www.dropbox.com/s/yhqvq6np66g352y/screencast%202019-11-01%2010-18-38.mp4
Fixed hover for nodeBlock display.
=> Hotfix-NB - Fixed hover on Nodeblock display.

modules/ding_app_variables/ding_app_variables.module
https://inlead.atlassian.net/browse/EASYOPAC-1183
Lists carousels added through the site without breaking original output format/structure.
None.
=> EASYOPAC-1183 - List all carousels maintaining data format.

themes/ddbasic/scripts/ddbasic.common.js
In case when the frontend layout has first region with class ".frontend-layout" empty, then all next regions with same class will be hidden, even if those are not empty.
=> NO-TASK - Process layout wrapper visibility correctly.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1234
Add `easyopac_abstracts_override` to easyopac.make file.
=> EASYOPAC-1234 - Adding module to easyopac.make.

ding2.make
https://www.drupal.org/node/1451868
=> EO-NO_TASK - Patch redirect module support encoding.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1251
Provides integration of  Unsplash with media manager. [Unsplash](https://unsplash.com/) is a source of free to use images.
How-to's:
https://www.drupal.org/project/media_unsplash
https://unsplash.com/documentation
=> EASYOPAC-1251 - Unsplash integration.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1255
During Unsplash image download, inserts alt/title values for the file entity, when applicable.
Null.
=> EASYOPAC-1255 - Unsplash alt/title placement patch.

project.make
https://inlead.atlassian.net/browse/EASYOPAC-1264
Update media_youtube module to the latest version.
=> EASYOPAC-1264 - Update media_youtube module.

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/js/video.js, modules/ding_nodelist/sass/ding_nodelist.scss, themes/ddbasic/sass/configuration/_extend.scss
https://inlead.atlassian.net/browse/EASYOPAC-1267
Fixing play and close buttons functionality on video items in promoted nodes widget and some small styling things.
=> EASYOPAC-1267 - Fix promoted nodes video behavior.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1262
Add new bibliofil_lists module to easyopac.make file.
=> EASYOPAC-1262 - Add bibliofil_lists to make file.

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/js/video.js, modules/ding_nodelist/plugins/content_types/ding_nodelist.inc, modules/ding_nodelist/sass/ding_nodelist.scss, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_news.carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_news.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_page.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_page.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist_widget_carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist_widget_promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist_widget_rolltab.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1272
This implements video view into Ding Nodelist's module Carousel  and  Rolltab widgets.
=> EASYOPAC-1272 - Implement video in Ding Nodelist widgets.

themes/ddbasic/sass/components/panel/class-panel.scss
Fixed width for body bibliotek
=> EO-NOTASK - Fixed width for library body.

modules/ding_library/ding_library.features.field_instance.inc
https://inlead.atlassian.net/browse/EASYOPAC-1282
Extends countries list in Ding Library node form.
=> EASYOPAC-1282 - Extend countries list on library node form.

project.make
https://inlead.atlassian.net/browse/EASYOPAC-1296
Fixes Field UI field's description translation.
=> EASYOPAC-1296 - Allow translation of field description.

themes/ddbasic/scripts/footer.js
https://inlead.atlassian.net/browse/BS-38
Added timeout for mobile footer menu js file.
https://www.hippovideo.io/video/play/aKtfQTglPCUS3savRBfD6jSfjfqHAaT5ie4kjYrrIVw
=> BS-38 - Added timeout for mobile footer menu js file.

ding2.bibliofil.inc, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.pages.inc, modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.theme.inc, modules/ding_reservation/ding_reservation.module, modules/ding_toggle_format/ding_toggle_format.module, project.make, themes/ddbasic/scripts/footer.js
https://inlead.atlassian.net/browse/EONO-14
Various installation improvements
=> EONO-14 - Various installation improvements

modules/ding_carousel/js/ding_carousel.js
https://inlead.atlassian.net/browse/EONO-27
=> EONO-27 - Clear previously selected carousel tabs.

modules/ding_ipe_filter/ding_ipe_filter.install, modules/ding_ipe_filter/ding_ipe_filter.module
https://inlead.atlassian.net/browse/EASYOPAC-1347
Adds "New custom content" option into IPE functionality.
=> EASYOPAC-1347 - Add 'New Custom Content' as a permanent in IPE.

modules/ding_ipe_filter/ding_ipe_filter.module
https://inlead.atlassian.net/browse/EASYOPAC-1347
Remove the pane title, if any, when enabling banner mode.
=> EASYOPAC-1347 - Remove any title if banner mode enabled.

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/ding_ddbasic_opening_hours.module
https://inlead.atlassian.net/browse/EASYOPAC-1342
Display localized categories labels  for the Opening Hours displays.
=> EASYOPAC-1342 - Show translated OH categories.

themes/ddbasic/scripts/footer.js
https://inlead.atlassian.net/browse/EASYOPAC-1352
Fix error on `gulp uglify` step in project build process.
=> EASYOPAC-1352 - Fixing error on js uglifying.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1336
Include module in make file.
=> EASYOPAC-1336 - Marc references module.

modules/ding_redirect/js/ding_redirect_login.js
https://inlead.atlassian.net/browse/EASYOPAC-1366
Wrapped user login JS functionality in Drupal behavior in order to have it properly processes by lazy pane functionality.
=> EASYOPAC-1366 - Fix redirect functionality on Lazy pane enabled panes.

themes/ddbasic/scripts/footer.js
https://inlead.atlassian.net/browse/EASYOPAC-1383
This reverts changes done in https://github.com/easySuite/ding2/pull/700.
=> EASYOPAC-1383 - Fix mobile menu toggle issue.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1391
Add "easyopac_wywsiwyg_button" module to .make file.
=> EASYOPAC-1391 - Extend WYSIWYG to allow adding buttons.
