themes/ddbasic/sass/components/class.scss
See: https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8
=> NO-TASK - Fetch iOS bugfix from foreign repo.

themes/ddbasic/template.node.php, themes/ddbasic/templates/node/node--ding-eresource--view-mode--teaser.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1008
"Read More" on /e-materialer page have duplicated language parameter in URL (/en/en/e-materialer/ereolen-1).
=> EASYOPAC-1008 - Refactor 'Read more' link.

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/modules/ding_place2book_migrate/ding_place2book_migrate.module
https://platform.dandigbib.org/issues/1404
Some more migration fixes.
During migration I got a lot of: `Error. updateEvent requires: [capacity]`
As it turns out, this is because the field_presave hook tries to sync with p2b API even when nodes are updated programmatically as in the migration. The easiest fix for this for both of these issues, seems to be checking for the precence of the capacity key in presave hook. It should still be possible to sync the node with p2b programmatically, one will just have to supply the capacity manually in the field item.
Also includes a fix the double ticket link in frontend issue, by ensuring that the p2b URL is remove from the external ticket_link field, since p2b now supplies it's field formatter which outputs its own field.
=> 1404 more migration fixes

modules/ding_place2book/ding_place2book.fields.inc, modules/ding_place2book/ding_place2book.module
Adds better handling of deletion of ticket types with sold tickets, by disabling the remove-button when this is the case. Also adds a note at the ticket type explaining why deletion is disabled.
@guddo We should have a talk about how to handle deletion of nodes (ding_event) with ticket types with sold tickets.
Note: I also sneaked in a small correction: The logic handling node/entity deletion is moved to the dedicated field hook (hook_field_delete). Since it's a field it's more correct to handle it here, will make it independent on which node/node_type/entity, the field is attached too.
=> 1404: Better handling of events with sold tickets

modules/ding_place2book/ding_place2book.module
The last fixes to get_event_state() before code review. Hope there's time to get this in.
Changes the code to use the correct active parameter on the event, when checking if the event is "paused".
Updates the code to first check for "sold out" and "waiting list" state. That we can possible completely avoid fetching ticket types if there's no avialable tickets. Also makes it possible to have a waiting list when sales are closed.
=> 1404: Get event state last fixes

modules/ding_sections/ding_sections.install
https://inlead.atlassian.net/browse/EASYOPAC-1032
Removed "ding_sections_custom_css" module from being enabled on "ding_sections" module installation.
=> EASYOPAC-1032 - Don't enable Custom CSS module on enable.

modules/ting_search_carousel/plugins/content_types/carousel.inc, modules/ting_search_carousel/ting_search_carousel.install
https://inlead.atlassian.net/browse/EASYOPAC-1030
We need to verify that ting_search_.carousel module is working as expected with the new changes, and that old carousels are kept.
=> EASYOPAC-1030 - Rename search key configs variable.

modules/ting_search_carousel/ting_search_carousel.install
https://inlead.atlassian.net/browse/EASYOPAC-1030
Update the migration process so the ting_search_carousels settings are kept in the database.
This PR will need to be reverted in future version
=> EASYOPAC-1030 - Migrate ting_searches to the searches settings.

modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.install
https://inlead.atlassian.net/browse/EASYOPAC-1051
On site build is running ding_update_7063 which is enabling ding_sections module and its submodules. The module ding_sections_term_panel is also installed and this tries to create field_term_page field in the database, which in case we already had easyddb_editorialbase_term_panel module enabled, was already created.
This commit adds additional check on module enable so we don't have conflicts regarding already existing field.
=> EASYOPAC-1051 - Sections: Check if field_term_page exists.

modules/ding_debt/plugins/content_types/debts/debts.inc, modules/ding_dibs/ding_dibs.admin.inc, modules/ding_event/ding_event.admin.inc, modules/ding_event/ding_event.module, modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/translations/da.po, modules/ding_nodelist/translations/general.pot, modules/ding_place2book/includes/ding_place2book.event_validate.inc, themes/ddbasic/template.node.php, themes/ddbasic/templates/node--newsletter.tpl.php, translations/da.po
https://inlead.atlassian.net/browse/EASYOPAC-1073
Several places I have seen "Kr" shown to the user instead of "kr.".
Please find out where this is happening and if its in code then change it, and if its a setting or in DB - let me know.
=> EASYOPAC-1073 - Use kr. instead of Kr.

themes/ddbasic/scripts/ddbasic.common.js
https://inlead.atlassian.net/browse/EASYOPAC-1072
Click on anchor links are not listening for page header height so the content to which page is scrolled is not visible.
=> EASYOPAC-1072 - Anchors not following viewport of content.

modules/ding_ipe_filter/ding_ipe_filter.install, modules/ding_ipe_filter/ding_ipe_filter.module, modules/ding_ipe_filter/includes/ding_ipe_filter.admin.inc
https://inlead.atlassian.net/browse/EASYOPAC-1071
When you are localadmin and located on https://www.katak.gl/da.
Then you can open IPE and see that "Ting Search Carousel" is not visible.
But if you change language to KL or EN, then its visible:
https://www.katak.gl/kl
https://www.katak.gl/en
IPE does not considers multiple languages.
=> EASYOPAC-1071 - Consider only pane subtype machine name.

modules/ding_event/ding_event.features.field_base.inc, modules/ding_news/ding_news.features.field_base.inc
https://inlead.atlassian.net/browse/EASYOPAC-1081
Changed the cardinality of the `title_image` field on `ding_news` and `ding_event` to support multiple images.
This has previously been located in easySuite/ding_nis but has now been moved here (to Core).
=> EASYOPAC-1081 - Default allow multiple news and event title images.

modules/ding_sections/ding_sections.module, modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
https://inlead.atlassian.net/browse/EASYOPAC-1091
New sections must listen to default panel variant which is stored in database and not the one from code.
=> EASYOPAC-1091 - Section-module term variant problem.

ding2.make
https://inlead.atlassian.net/browse/EASYOPAC-1089
Mark OG menu links as `customized` so they persist after cache clear. This is a workaround, no root reason for this bug was found yet.
None.
Void.
=> EASYOPAC-1089 - Persist og menu links patch.

modules/ding_campaign/ding_campaign.module
https://inlead.atlassian.net/browse/EASYOPAC-1101
Changed the order of SQL query results because 'DESC' order was pushing negative weight into the end of results array, what is disagreeing with default Drupal weighting functionality when negative values have higher weight than positives one.
=> EASYOPAC-1101 - Culture: Grid campaign not listening to weight.

modules/ding_reservation/ding_reservation.module
https://inlead.atlassian.net/browse/EASYOPAC-977
Functionality moved to https://github.com/easySuite/ding_reservation_settings/pull/6.
No other method could find other then alter hook menu.
Tried to inject into the hook_provider_invoke, but this solution requires definition of another provider with all its related hooks. Also, tried inject into the hook_ding_entity_button to alter the reservation link, but the result does not differ from this one. Tried to inject into the ding_reservation_reserve_form but the solution is more hacky than this.
=> EASYOPAC-977 - Remove quick reservation functionality.

modules/ding_nodelist/ding_nodelist.module
Wrong mechanism for translating "More link" labels for nodelists was chosen. This PR fixes this issue and the label as a string will be available in translation interface instead of token.
=> HOTFIX - Translate 'More link' for nodelist panes.

modules/ding_ddbasic/modules/ding_ddbasic_opening_hours/plugins/content_types/weekly_opening_hours.inc
https://inlead.atlassian.net/browse/EASYOPAC-1142
In ding_library content type settings we have config option "Hide opening hours if not one wasn't added." which is responsible of hiding or displaying OH block/pane on libraries pages.
There was an issue that this option didn't had any effect - this commit fixes this issue.
=> EASYOPAC-1142 - Hide OH on Library if empty checked.

modules/ding_base/ding_base.module
EASYOPAC-NO_TASK - Proper quality setting when saving png images.
None. Hotfix.
Images that are png files are faulty saved. The reason behind this is wrong `imagepng` third arguments value, which can onle be compression value within 0-9.
None.
None.
=> EASYOPAC-NO_TASK

modules/ding_event/ding_event.module
PROD issue.
In case when Event list page filters are empty, the additional conditions added in code to views query were added in the wrong place, so it was trying to add code into filter which was an instance of SelectQuery class.
=> NO-TASK - Event list filtering fix.

modules/ting_search_carousel/plugins/content_types/carousel.inc, modules/ting_search_carousel/ting_search_carousel.module
https://inlead.atlassian.net/browse/EASYOPAC-1179
Requests take to long when saving Panels that has carousel and it causes AJAX error to occur:
https://www.dropbox.com/s/xmcssup3qtqvl4x/ajax-error.mp4?dl=0
=> EASYOPAC-1179 - Clear carousel code.

modules/ding_event/ding_event.module
https://inlead.atlassian.net/browse/EASYOPAC-1111
If all related events are grouped then need to hide the duplicates from the search view, front page view.
=> EASYOPAC-1111 - Group events by title, date, library.

modules/ding_nodelist/ding_nodelist.module, modules/ding_sections/ding_sections.module
https://inlead.atlassian.net/browse/EASYOPAC-1169
he dblog is spammed with php notices that makes debugging of rare occurring events practically impossible.
Since these php notices are a sign of some unexpected behavior or code faulty we anyway need to get rid of them.
The goal is that dblog is indeed for logging important things.
=> EASYOPAC-1169 - Ensure variables are properly parsed.

ding2.info, ding2.install, easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1195
Added ting_recommender module in easyopac.make file and enable this on site installation or updates execution.
=> EASYOPAC-1195 - Build and enable ting_recommender module.

modules/ding_frontend/ding_frontend.module, modules/ding_frontend/js/ding_frontend.js, modules/ding_frontend/templates/ding-frontpage--views-exposed-form-widget.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1171
Added autocomplete tag filter functionality for Editorial Content search.
=> EASYOPAC-1171 - Tags autocomplete filter on editorial search.

themes/ddbasic/sass/components/ding-carousel.scss, themes/ddbasic/sass/components/field.scss
https://inlead.atlassian.net/browse/EASYOPAC-1201
Changing sizing of carousels elements in order to have 5 items in carousel and save some useful space on frontend UI.
=> EASYOPAC-1201 - Cover images should be smaller in all carousels.

modules/ding_app_variables/ding_app_variables.module
https://inlead.atlassian.net/browse/EASYOPAC-1183
Identify all front-page carousels with same `carousel` identifier, so mobile app is aware of them.
See https://github.com/easySuite/ding2/pull/628 for initial change-set.
=> EASYOPAC-1183 - Identify all front-page carousels.

modules/ding_frontend/ding_frontend.features.inc
Ding page CT's body field was changed to use paragraphs functionality. Paragraphs entity have it's own fields which wasn't added to Search API index used for nodes search.
In this PR is added paragraphs text field to search index.
Ensure `default_multiple_index` (@/admin/config/search/search_api/index/default_multiple_index) index is re-indexed after changes deploy.
=> NO-TASK - Add paragraphs and paragraphs text field to search index.

themes/ddbasic/utils.inc
Ting search carousels could not be saved in the IPE view. The problem occurs when the title or description of the ting object is truncated in the "middle" special character. E.g. æ in the word Kælderbiblioteket.
=> NO_TASK - Consider special characters on tring truncation.

themes/ddbasic/scripts/account.js
In user profile's lists (loan/debts/reservation) overall table heading must be sticky, but it's not, on page scroll it is not visible because it's hidden under search form.
=> SUP-1805 - Sticky header in profile lists is on top of list.

modules/ting_field_search/ting_field_search.module
Adding functionality for making possible to translate title of search profiles.
After delivering code:
1. Clear cache
2. Visit any page where is present search form with search profiles
3. Go to `/admin/config/regional/translate/translate` page, from `Limit search to`  filter select list choose **Ting Field Search**, after that you'll see in table below all Ting Search Profile titles with the possibility to translate them.
I've tried to move this out of the core, but this is not possible in this case.
=> SUP-1879 - Possibility to translate titel of search profiles.

themes/ddbasic/scripts/ddbasic.common.js
When we have more than 1 panel pane of type ding_nodelist with selected "Promoted nodes" widget on one page, items from the rest of "Promoted nodes" nodelists are linking to the items from the first one.
=> NO-TASK - Nodelist Promoted node items are linking to wrong nodes.

modules/ting_search_carousel/plugins/content_types/carousel.inc
https://inlead.atlassian.net/browse/EASYOPAC-1224
Title of the ting search carouse pane is not added on first pane insert.
=> EASYOAPC-1224 - Set title configs on ting search carousel.

modules/ting/js/ting_ding_entity_buttons.js, modules/ting/ting.module, modules/ting_infomedia/ting_infomedia.module
Re-implement AJAXified Ting (See online, Other formats) and Ting Infomedia (Read article) entity buttons, because this was generating severak requests to Opensearch.
=> NO-TASK - Re-implement AJAXified entity buttons.

easyopac.make, modules/ding_nodelist/templates/ding_nodelist.ding_event.carousel.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.grid_images.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.horizontal_accordion.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.minimal_display.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.node_blocks.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.promoted_nodes.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.slider.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_event.taxonomy.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_page.rolltab.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1233
In order to have possibility to pass any attributes to ding_nodelist event templates, was added ```$attributes``` variable which is processed automatically by drupal and renders all attributes passed in preproces functions.
Those changes have to be merged and deployed in order to have module ```easyddb_event_status``` working.
=> EASYOPAC-1233 - Status display on Event CTs.

modules/ding_adgangsplatformen/ding_adgangsplatformen.module, modules/ding_user/ding_user.module
None.
Removes the language prefix from redirection url's generated during 3rd party logins. If language detection is set to url, the language prefix is prepended to the redirection route and eventually, is fed to `drupal_goto` -> `url` which prepends language prefix again.
None.
Can only be tested @ production.
=> EASYOPAC-NO_TASK - Omit the language prefix from redirect url.

modules/ding_mobilesearch/plugins/rest.inc
https://inlead.atlassian.net/browse/EASYOPAC-1226
When _mobilesearch_ push debug is on, it is logging the full payload into the _dblog_. So whether an image was a part the payload it would eventually be written into the log as a huge base64 encoded data. This could possibly result in mysql failure, like _gone away_ error. The change-set, limits the logged data to a reasonable value.
Before:
After:
None.
=> EASYOPAC-1226 - Ease the debug info.

modules/ding_mobilesearch/ding_mobilesearch.module
https://inlead.atlassian.net/browse/EASYOPAC-1237
Nothing to be done. Fields of that type are covered by default and are pushed automatically.
Left a note in code in regards to pushing specifics when mongo uses a text-index.
=> EASYOPAC-1237 - Push event status label and color.

themes/ddbasic/templates/node/node--ding-event.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1238
Price value was displayed in wrong position. This reverts changes added in https://github.com/easySuite/ding2/pull/415.
=> EASYOPAC-1238 - Revert PR 415.

modules/ding_news/ding_news.strongarm.inc
https://inlead.atlassian.net/browse/EASYOPAC-1231
Right now, the webform field is inserted as the last element on a node CT. It means that user think the "article is finished". The webform should be moved right after Paragraph / before Files.
=> EASYOPAC-1231 - Webform should be inserted right after Paragraphs.

modules/ding_app_smartbanner/ding_app_smartbanner.admin.inc, modules/ding_app_smartbanner/js/ding_app_smartbanner.js
https://inlead.atlassian.net/browse/EASYOPAC-1235
In the Bibliofil-project, the smartbanner is shown when running inside the Application itself and calling to install this. As the Bibliofil app developers added customized User Agent string ``` "Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Bibliofil MappaMiWebApp - iOS"```, we will look into User Agent string and if it will match "bibliofil" key, we'll skip initialization of smart banner.
=> EASYOPAC-1235 - Custom hack for the smartbanner module

modules/ting_search_carousel/ting_search_carousel.module
https://inlead.atlassian.net/browse/EASYOPAC-1245
Carousel item's description is not readable after changes made for displaying smaller cover images.
This PR hides ting_object's ```ting_abstract``` field for carousel items.
=> EASYOPAC-1245 - Hide description of items in carousel.

modules/ding_event/ding_event.features.field_instance.inc
https://inlead.atlassian.net/browse/EASYOPAC-1244
The price field in Event CT is mandatory. This is creating some kind of misunderstanding because in more places we can notice that ```if you leave field blank it will say "Free"```, but real situation is that user if forced to fill this field otherwise he can't save node.
This commit makes "Price" field non-mandatory.
=> EASYOPAC-1244 - Make price field non-mandatory.

modules/ding_event/ding_event.module
https://inlead.atlassian.net/browse/EASYOPAC-1249
Event with list filter "Vis på dags dato, så begivenheden er synlig hver dag den foregår." is not shown on events oveview page.
=> EASYOPAC-1249 - Fix list filter appending to query.

modules/ting/ting.module, themes/ddbasic/scripts/ting-object/ting-object.js
On "Other format" button click, there was appearing an alert with JS error.
=> NO-TASK - Fix entity buttons behavior.

modules/ding_content/ding_content.features.filter.inc
https://inlead.atlassian.net/browse/BS-37
<b> tag was excluded from rendering on content display.
=> BS-37 - Add <b> tag as allowed to ding_wysiwyg text format.

modules/ding_library/plugins/content_types/address.inc
The "Address 2" field of Library CT was not displayed on the library overview page.
=> EO-NOTASK - Display Address 2 line on library overview.

modules/ting/js/ting_ding_entity_buttons.js
https://inlead.atlassian.net/browse/EASYOPAC-1263
Ding entity buttons might happen to be invoked simultaneously, which might create a case when database tries to write same record twice. This eventually triggers database exception regarding duplicate values.
None.
This PR would simply make entity buttons wait each other and run consequently.
=> EASYOPAC-1263 - Invoke entity buttons consequently.

project.make
https://inlead.atlassian.net/browse/EASYOPAC-1267
Updated manualcrop contrib module to latest version because previous version wasn't  check for file entity type and in case of video attached through media browse it was throwing an JS error.
=> EASYOPAC-1267 - Update manualcrop contrib module.

themes/ddbasic/scripts/node/news.js
https://inlead.atlassian.net/browse/EASYOPAC-1269
Lead/body text is not displayed for the wide teaser on ding_news_frontpage view.
=> EASYOPAC-1269 - Lead text is not displayed on ding_news_frontpage.

modules/ding_availability/js/ding_availability.js, modules/ding_availability/js/ding_availability_labels.js, modules/fbs/includes/fbs.reservation.inc
https://inlead.atlassian.net/browse/EASYOPAC-1271
On non-cached material item page render which has periodical issues available for reservation, reservation link's 'use-ajax' class wasn't processed correctly and 'ajax-processed' class wasn't added and as a result the ajaxify functionality wasn't triggered.
The forced attaching of Drupal behaviors fixes this.
Also in this PR were added missing response types returned from FBS and fixed reservation buttons behavior.
=> EASYOPAC-1271 - Re-attach behaviors on availability processing.

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/js/video.js, modules/ding_nodelist/sass/ding_nodelist.scss, modules/ding_nodelist/templates/ding_nodelist.ding_eresource.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist.ding_page.rolltab.tpl.php, modules/ding_nodelist/templates/ding_nodelist_widget_rolltab.tpl.php, modules/ding_tabroll/ding_tabroll.module
https://inlead.atlassian.net/browse/EASYOPAC-1276
Remove support of videos in Ding Nodelist's rolltab widget.
=> EASYOPAC-1276 - Remove video support for nodelist's tabroll.

modules/ding_availability/js/ding_availability.js
https://inlead.atlassian.net/browse/EASYOPAC-1292
Search expand button was not working on item page because the `Drupal.attachBehaviors()` in ding_availability.js was duplicating called actions, so as for search expand button was used jQuery `toggle()` function this on click was called twice.
=> EASYOPAC-1292 - Search expand button is not working on item page.

modules/ding_mobilesearch/ding_mobilesearch.install
https://inlead.atlassian.net/browse/EASYOPAC-1298
Modified `ding_mobilesearch` `hook_uninstall()` so on module uninstalling the variables used by `flag` module are deleted and also `push_to_mongo` flag option is deleted from database table.
=> EASYOPAC-1298 - Delete stale variables and settings from database.

ding2.info, modules/ding_sections/ding_sections.install, modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.install
https://inlead.atlassian.net/browse/EASYOPAC-1308
Fixing errors appearing on `ding_section` install in profile installation process and add missing dependency to `i18n_string` module.
=> EASYOPAC-1308 - Fix errors breaking profile installation process.

ding2.bibliofil.inc, ding2.profile, easyopac.make
https://inlead.atlassian.net/browse/EONO-7
Added additional steps into ding2 profile installer which will automatically enable required modules, add Norwegian language and import localization files and disable un-needed modules.
Localization files will be kept in easySuite/bibliofil_common repo.
=> EONO-7 - Extending ding2 profile installer with new steps.

modules/fbs/fbs.module, modules/fbs/includes/fbs.availability.inc
https://inlead.atlassian.net/browse/EASYOPAC-1330
Removed the piece of code responsible for fetching the DK5 field value into holdings.
=> EASYOAPC-1330 - Strip DK5 from holdings.

modules/ding_staff/ding_staff.module
https://inlead.atlassian.net/browse/EASYOPAC-1341
Because of profile2 entity specific behavior which is not allowing field values translation, process the 'position' field with `t()` function.
=> EASYOPAC-1341 - Translation of Staff Position.

easyopac.make
https://inlead.atlassian.net/browse/EASYOPAC-1336
Add custom `easyopac_marc_references` module into make file.
=> EASYOPAC-1336 - Add easyopac_marc_references module to make file.

modules/ding_ipe_filter/ding_ipe_filter.module
https://inlead.atlassian.net/browse/EASYOPAC-1347
In order to handle the color containing fields, was implemented custom form field type `<input type="color">`. This represents an color picker which allow visual color selection for end-user.
=> EASYOPAC-1347 - Implement color custom field element.

modules/ding_nodelist/ding_nodelist.module
https://inlead.atlassian.net/browse/EASYOPAC-1360
Check if node has translations and replace the `nid` in the array passed for rendering.
=> EASYOPAC-1360 - Load translated nodes for nodelist widgets.

project.make, themes/ddbasic/scripts/view.js
https://inlead.atlassian.net/browse/EASYOPAC-1327
Updating Masonry JS library to the latest version which introduces ordering of grid items and add `horizontalOrder` property to ding event list view.
=> EASYOPAC-1327 - Wrong sorting order for events.

modules/ding_nodelist/ding_nodelist.module
https://inlead.atlassian.net/browse/EASYOPAC-1293
The issue belongs to wrong sorting logic of nodes by creation date, because it didn't take in consideration the aspect that creation date can be the same for multiple nodes.
Here we are checking if the already sorted nodes have the same key as processed node's created date, if this is true - then adding iteration counter to the array key.
=> EASYOPAC-1293 - Fix nodes sorting by 'creation date'.

modules/ding_nodelist/ding_nodelist.module, modules/ding_nodelist/templates/ding_nodelist.ding_event.slider.tpl.php
https://inlead.atlassian.net/browse/EASYOPAC-1368
In case of items sorting by events date, the node object is wrapped into an array item with event date timestamp as a key for further sorting and when it comes the time for rendering the node object is not found and page fails to load with critical error.
=> EASYOPAC-1368 - Sorting by event date breaks the site.

modules/ding_nodelist/css/ding_nodelist.css, modules/ding_nodelist/js/node_blocks.js, modules/ding_nodelist/sass/ding_nodelist.scss
https://inlead.atlassian.net/browse/EASYOPAC-1373
Fixed height for nodeblocks display.
=> EASYOPAC-1373 - Fix height for nodeblocks.
